import React from "react";

export const users = [
  {
    key: "1",
    name: "Mr. S RAMALINGAM",
    role: "National President",
    address: "Anand Apartments, 262/11 Poonamallee High Road, Kilpauk, CHENNAI 600 010",
    phonenumber: "96770 11766",
    email: "ramaling37@yahoo.co.in",
  },
  {
    key: "2",
    name: "Mr. K SADASIVA CHETTY",
    role: "Vice President – HQ",
    address: "G-4,Ground Floor, Kala Flats, New No.15 Kamatchipuram 2nd Street, West Mambalam, CHENNAI 600 033",
    phonenumber: "98410 46289",
    email: "sada1339@yahoo.co.in",
  },
  {
    key: "3",
    name: "Mr. R SUNDAR",
    role: "Vice-President – Southern Region",
    address: "Director Of Boilers, North Wing, Pwd Office Compound, 1st Floor, Chepauk, CHENNAI 600 005",
    phonenumber: "94430 01763",
    email: "eramsun@gmail.com",
  },
  {
    key: "4",
    name: "Mr. RAMNATH S MANI",
    role: "Vice President – Eastern Region",
    address: "New 27, Old 14, Josier Street, 2nd. Floor, Nungambakkam, CHENNAI – 600034",
    phonenumber: "O +91 44 28266227, 98400 62118",
    email: "rsmani@automationexcellence.com",
  },
  {
    key: "5",
    name: "CAPT. DINESH T S R",
    role: "Secretary",
    address: "Director, Praddin Power Pvt Ltd., No.4 N S K Street, Eswaran Nagar, Pammal, CHENNAI 600 075",
    phonenumber: "98842 03213",
    email: "dinesh@praddinenergy.in",
  },
  {
    key: "6",
    name: "Mr. S SAKTHIVEL",
    role: "Treasurer",
    address: "Dy. Director Of Boilers, A 5/1 BHEL Quarters, Kailasapuram, TRICHY 620 014",
    phonenumber: "94431 49993",
    email: "shasvgl@yahoo.com",
  },
  {
    key: "7",
    name: "Mr. PRADEEP CHAND KRD",
    role: "Joint Secretary",
    address: "Senior Manager (Shift Operations), Chennai Petroleum Corporation Ltd, Manali, CHENNAI 600068",
    phonenumber: "94455 76307",
    email: "krdpchand@cpcl.co.in",
  },
  {
    key: "8",
    name: "Mr. S JEYARAM",
    role: "Joint Secretary",
    address: "New No. 34 Mannaar Second St., Nerkundrum Pathai i, Vadapalani, CHENNAI 600 026",
    phonenumber: "97910 20132",
    email: "sjeyaram@hotmail.com",
  },
  {
    key: "9",
    name: "Mr. MADHAVAN NAMPOOTHIRI",
    role: "ENFUSE Journal Editor",
    address: "New No.7 Malleeswarar Koil St., Mylapore, CHENNAI 600 004",
    phonenumber: "8939724520",
    email: "madhavan@re-solve.in",
  },
  {
    key: "10",
    name: "Mr. R RAJU PANDI",
    role: "Chairman – Power Generation Sector",
    address: "Flat No. 9, 3rd Floor, Hemamanor, 23 Branson Garden Street, Kelly’s, CHENNAI 600 010",
    phonenumber: "94449 22954",
    email: "rajupandi@hotmail.com",
  },
  {
    key: "11",
    name: "Mr. S BASKARA SETHUPATHY",
    role: "Chairman – Academic Interface",
    address: "Professor and Head, Department of Civil Engineering, S.A. Engineering college, CHENNAI 600 077",
    phonenumber: "9445633381",
    email: "sethu_lotus@yahoo.co.in",
  },
  {
    key: "12",
    name: "Mr. G THANGARAJ",
    role: "Chairman – Rural Energy",
    address: "81 South West Boag Road, T Nagar, CHENNAI 600 017",
    phonenumber: "98402 61978",
    email: "lionthangaraj@yahoo.com",
  },
  {
    key: "13",
    name: "MR. S R PRADHISH KUMAAR",
    role: "Chairman– New Renewable Energy",
    address: "Director, Praddin Power Pvt Ltd., No.4 N S K Street, Eswaran Nagar, Pammal, CHENNAI 600 075",
    phonenumber: "99401 50530",
    email: "pradhishkumar@praddinenergy.in",
  },
  {
    key: "14",
    name: "Mr. K R GOVINDAN",
    role: "Task Group Member",
    address: "New No.22 Janakiram Street West Mambalam, CHENNAI 600 033",
    phonenumber: "94443 82649",
    email: "krgovindan@vsnl.com",
  },
  {
    key: "15",
    name: "Mr. B SREERAMA SREENIVASU",
    role: "Coordinator – Pune",
    address: "Flat No. 603, Block D-2, Mahalaxmi Vihar, Vishrantwadi, PUNE – 411 015",
    phonenumber: "099701-94339",
    email: "sreeram_vasu@yahoo.com",
  },
  {
  key: "16",
  name: "Mr. D. ANANTHANARAYANAN",
  role: "Coordinator – Narimanam Region",
  address: "Manager (P&A), Chennai Petroleum Corpn Ltd Cauvery Basin Refinery Panangudi, Nannilam 0Taluk NAGAPATTINAM 611 002",
  phonenumber: "Ph. 04365 – 256403, 94430 71432",
  email: "da@cpcl.co.in",
},
{
  key: "17",
  name: "Mr. G L SRINIVASAN",
  role: "Member – Immediate Past President",
  address: "New6/2, Old 17/2, Raghu Veda Apartments, Jagadeeswaran St, T Nagar, CHENNAI 600017",
  phonenumber: "94449 07738",
  email: "geeyeles@yahoo.com",
},
{
  key: "18",
  name: "Mr. S ARUL",
  role: "Member",
  address: "98408 70075",
  email: "arul@aruldesign.com",
},
{
  key: "19",
  name: "Mr. T DORAIVEL",
  role: "Member",
  address: "NO.5 First Street, East Abhiramapuram, CHENNAI 600 004",
  phonenumber: "94441 85424",
  email: "doraivel_@hotmail.com",
},
{
  key: "20",
  name: "Mr. V KANNIAPPAN",
  role: "Member",
  address: "President, Aban Offshore Ltd., Janpriya Crest, 113 Pantheon Road, CHENNAI 600 008",
  phonenumber: "098403 04533",
  email: "kanniappanvvm@gmail.com",
},
{
    key: "21",
    name: "Dr. B V S LAKSHMI",
    role: "Member",
    address: "G-2,5-10-197/2, Hill Fort Road, Adarsh Nagar, HYDERABAD 500 004",
    phonenumber: "098481 99200",
    email: "sreeramvasu@vsnl.net",
  },
  {
    key: "22",
    name: "Mr. S PANDARINATHAN",
    role: "Member",
    address: "G M (Dev), CPCL (Retd), #7, Nathamuni 2nd Cross Street, Naduvankarai, Anna Nagar, CHENNAI 600 040",
    phonenumber: "94443 90012",
    email: "spnathan1341@yahoo.co.in",
  },
  {
    key: "23",
    name: "Dr. A. PEER FATHIMA",
    role: "Member",
    address: "Professor, School of Electrical Engineering(SELECT), VIT , Chennai, Vandalur-Kelambakkam Road, CHENNAI – 600 127",
    phonenumber: "9444022777",
    email: "peerfathima.a@vit.ac.in",
  },
  {
    key: "24",
    name: "Mr. A RAJENTHRAN",
    role: "Member",
    address: "Block No.C1, Pranavam Apartments, Plot No.3, Kamadhenu 2nd St. Mogappair East, CHENNAI 600 037",
    phonenumber: "Ph. 26564181, 94441 45833",
    email: "arajenthran@yahoo.in",
  },
  {
    key: "25",
    name: "Mr. C RAJESH SRINIVASAN",
    role: "Member",
    address: "Project Manager, Cape Energy Pvt Ltd, 4-D, 4th Floor, Century Plaza, No.560-562 Anna Salai, Teynampet, CHENNAI 600 018",
    phonenumber: "92837 01460",
    email: "crs.rajesh@gmail.com",
  },
  {
    key: "26",
    name: "CAPT M SINGARAJA",
    role: "Member",
    address: "Ratnabala Designs & Consultants, New No.90 Rama Naicken St., Nungambakkam, CHENNAI 600 034",
    phonenumber: "94441 27704",
    email: "singaraja@gmail.com",
  },
  {
    key: "27",
    name: "Dr R VENKATRAMAN",
    role: "Member",
    address: "Door No.7, 3rd Cross, 5th Main Road, Srinivasa Nagar South, TRICHY 620 017",
    phonenumber: "99427 62255 / 94434 92404",
    email: "avr2s@rediffmail.com / avrr22s@gmail.com",
  },
  
];
